// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement() {
  return window['go']['main']['CounterDemo']['Decrement']();
}

export function GetCount() {
  return window['go']['main']['CounterDemo']['GetCount']();
}

export function Increment() {
  return window['go']['main']['CounterDemo']['Increment']();
}

export function SetStateFile(arg1) {
  return window['go']['main']['CounterDemo']['SetStateFile'](arg1);
}

export function Shutdown() {
  return window['go']['main']['CounterDemo']['Shutdown']();
}

export function Startup() {
  return window['go']['main']['CounterDemo']['Startup']();
}
