// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement():Promise<number>;

export function GetCount():Promise<number>;

export function Increment():Promise<number>;

export function SetStateFile(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup():Promise<void>;
