// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement():Promise<number>;

export function GetCount():Promise<number>;

export function Increment():Promise<number>;
