// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement() {
  return window['go']['main']['CounterDemo']['Decrement']();
}

export function GetCount() {
  return window['go']['main']['CounterDemo']['GetCount']();
}

export function Increment() {
  return window['go']['main']['CounterDemo']['Increment']();
}
