// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.DownloadState>;

export function Reset():Promise<main.DownloadState>;

export function StartDownload(arg1:string):Promise<main.DownloadState>;

export function SyncLanguage():Promise<void>;
