// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['DownloadDemo']['GetState']();
}

export function Reset() {
  return window['go']['main']['DownloadDemo']['Reset']();
}

export function SetContext(arg1) {
  return window['go']['main']['DownloadDemo']['SetContext'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['DownloadDemo']['StartDownload'](arg1);
}
